Traceback (most recent call last):
  File "d:\007Github\pythonVB\.venv\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "d:\007Github\pythonVB\.venv\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\007Github\pythonVB\.venv\Lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ilker.arslan\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "d:\007Github\pythonVB\.venv\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "d:\007Github\pythonVB\.venv\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "d:\007Github\pythonVB\.venv\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print(karekok(-16))
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
Cell [1;32mIn[14], line 1[0m
[1;32m----> 1[0m [38;5;28mprint[39m([43mkarekok[49m[43m([49m[38;5;241;43m-[39;49m[38;5;241;43m16[39;49m[43m)[49m)

Cell [1;32mIn[13], line 3[0m, in [0;36mkarekok[1;34m(girdi)[0m
[0;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mkarekok[39m(girdi):
[0;32m      2[0m     [38;5;28;01mif[39;00m girdi [38;5;241m<[39m [38;5;241m0[39m:
[1;32m----> 3[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mEksi bir sayÄ± girdiniz!!![39m[38;5;124m"[39m)
[0;32m      4[0m     [38;5;28;01mtry[39;00m:
[0;32m      5[0m         [38;5;28;01mreturn[39;00m girdi [38;5;241m*[39m[38;5;241m*[39m [38;5;241m0.5[39m

[1;31mValueError[0m: Eksi bir sayÄ± girdiniz!!!

